# Generated by Django 5.2.10 on 2026-01-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.FloatField(default=0)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(blank=True, null=True)),
                ('total_on_duty_hours', models.FloatField(blank=True, null=True)),
                ('num_days_required', models.IntegerField(default=1)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('compliance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField(default=1)),
                ('timeline_data', models.JSONField(default=list)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('total_sleeper_berth_hours', models.FloatField(default=0)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_miles', models.FloatField(default=0)),
                ('carrier_name', models.CharField(default='FMCSA Carrier', max_length=255)),
                ('carrier_address', models.CharField(default='City, State', max_length=255)),
                ('driver_name', models.CharField(default='Driver Name', max_length=255)),
                ('vehicle_number', models.CharField(default='', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip')),
            ],
            options={
                'ordering': ['date', 'day_number'],
            },
        ),
    ]
